// flags.js
const flags = {
  ad: { name: 'Andorra', img: 'flags/ad.png' },
  ae: { name: 'United Arab Emirates', img: 'flags/ae.png' },
  af: { name: 'Afghanistan', img: 'flags/af.png' },
  ag: { name: 'Antigua and Barbuda', img: 'flags/ag.png' },
  ai: { name: 'Anguilla', img: 'flags/ai.png' },
  al: { name: 'Albania', img: 'flags/al.png' },
  am: { name: 'Armenia', img: 'flags/am.png' },
  ao: { name: 'Angola', img: 'flags/ao.png' },
  aq: { name: 'Antarctica', img: 'flags/aq.png' },
  ar: { name: 'Argentina', img: 'flags/ar.png' },
  as: { name: 'American Samoa', img: 'flags/as.png' },
  at: { name: 'Austria', img: 'flags/at.png' },
  au: { name: 'Australia', img: 'flags/au.png' },
  aw: { name: 'Aruba', img: 'flags/aw.png' },
  ax: { name: 'Åland Islands', img: 'flags/ax.png' },
  az: { name: 'Azerbaijan', img: 'flags/az.png' },
  ba: { name: 'Bosnia and Herzegovina', img: 'flags/ba.png' },
  bb: { name: 'Barbados', img: 'flags/bb.png' },
  bd: { name: 'Bangladesh', img: 'flags/bd.png' },
  be: { name: 'Belgium', img: 'flags/be.png' },
  bf: { name: 'Burkina Faso', img: 'flags/bf.png' },
  bg: { name: 'Bulgaria', img: 'flags/bg.png' },
  bh: { name: 'Bahrain', img: 'flags/bh.png' },
  bi: { name: 'Burundi', img: 'flags/bi.png' },
  bj: { name: 'Benin', img: 'flags/bj.png' },
  bl: { name: 'Saint Barthélemy', img: 'flags/bl.png' },
  bm: { name: 'Bermuda', img: 'flags/bm.png' },
  bn: { name: 'Brunei Darussalam', img: 'flags/bn.png' },
  bo: { name: 'Bolivia, Plurinational State of', img: 'flags/bo.png' },
  bq: { name: 'Caribbean Netherlands', img: 'flags/bq.png' },
  br: { name: 'Brazil', img: 'flags/br.png' },
  bs: { name: 'Bahamas', img: 'flags/bs.png' },
  bt: { name: 'Bhutan', img: 'flags/bt.png' },
  bv: { name: 'Bouvet Island', img: 'flags/bv.png' },
  bw: { name: 'Botswana', img: 'flags/bw.png' },
  by: { name: 'Belarus', img: 'flags/by.png' },
  bz: { name: 'Belize', img: 'flags/bz.png' },
  ca: { name: 'Canada', img: 'flags/ca.png' },
  cc: { name: 'Cocos (Keeling) Islands', img: 'flags/cc.png' },
  cd: { name: 'Congo, the Democratic Republic of the', img: 'flags/cd.png' },
  cf: { name: 'Central African Republic', img: 'flags/cf.png' },
  cg: { name: 'Republic of the Congo', img: 'flags/cg.png' },
  ch: { name: 'Switzerland', img: 'flags/ch.png' },
  ci: { name: 'Côte d\'Ivoire', img: 'flags/ci.png' },
  ck: { name: 'Cook Islands', img: 'flags/ck.png' },
  cl: { name: 'Chile', img: 'flags/cl.png' },
  cm: { name: 'Cameroon', img: 'flags/cm.png' },
  cn: { name: 'China (People\'s Republic of China)', img: 'flags/cn.png' },
  co: { name: 'Colombia', img: 'flags/co.png' },
  cr: { name: 'Costa Rica', img: 'flags/cr.png' },
  cu: { name: 'Cuba', img: 'flags/cu.png' },
  cv: { name: 'Cape Verde', img: 'flags/cv.png' },
  cw: { name: 'Curaçao', img: 'flags/cw.png' },
  cx: { name: 'Christmas Island', img: 'flags/cx.png' },
  cy: { name: 'Cyprus', img: 'flags/cy.png' },
  cz: { name: 'Czech Republic', img: 'flags/cz.png' },
  de: { name: 'Germany', img: 'flags/de.png' },
  dj: { name: 'Djibouti', img: 'flags/dj.png' },
  dk: { name: 'Denmark', img: 'flags/dk.png' },
  dm: { name: 'Dominica', img: 'flags/dm.png' },
  dr: { name: 'Dominican Republic', img: 'flags/dr.png' },
  dz: { name: 'Algeria', img: 'flags/dz.png' },
  ec: { name: 'Ecuador', img: 'flags/ec.png' },
  ee: { name: 'Estonia', img: 'flags/ee.png' },
  eg: { name: 'Egypt', img: 'flags/eg.png' },
  eh: { name: 'Western Sahara', img: 'flags/eh.png' },
  er: { name: 'Eritrea', img: 'flags/er.png' },
  es: { name: 'Spain', img: 'flags/es.png' },
  et: { name: 'Ethiopia', img: 'flags/et.png' },
  eu: { name: 'Europe', img: 'flags/eu.png' },
  fi: { name: 'Finland', img: 'flags/fi.png' },
  fj: { name: 'Fiji', img: 'flags/fj.png' },
  fk: { name: 'Falkland Islands (Malvinas)', img: 'flags/fk.png' },
  fm: { name: 'Micronesia, Federated States of', img: 'flags/fm.png' },
  fo: { name: 'Faroe Islands', img: 'flags/fo.png' },
  fr: { name: 'France', img: 'flags/fr.png' },
  ga: { name: 'Gabon', img: 'flags/ga.png' },
  gb: { name: 'United Kingdom', img: 'flags/gb.png' },
  gbeng: { name: 'England', img: 'flags/gbeng.png' },
  gbnir: { name: 'Northern Ireland', img: 'flags/gbnir.png' },
  gbsct: { name: 'Scotland', img: 'flags/gbsct.png' },
  gbwls: { name: 'Wales', img: 'flags/gbwls.png' },
  gd: { name: 'Grenada', img: 'flags/gd.png' },
  ge: { name: 'Georgia', img: 'flags/ge.png' },
  gf: { name: 'French Guiana', img: 'flags/gf.png' },
  gg: { name: 'Guernsey', img: 'flags/gg.png' },
  gh: { name: 'Ghana', img: 'flags/gh.png' },
  gi: { name: 'Gibraltar', img: 'flags/gi.png' },
  gl: { name: 'Greenland', img: 'flags/gl.png' },
  gm: { name: 'Gambia', img: 'flags/gm.png' },
  gn: { name: 'Guinea', img: 'flags/gn.png' },
  gp: { name: 'Guadeloupe', img: 'flags/gp.png' },
  gq: { name: 'Equatorial Guinea', img: 'flags/gq.png' },
  gr: { name: 'Greece', img: 'flags/gr.png' },
  gs: { name: 'South Georgia and the South Sandwich Islands', img: 'flags/gs.png' },
  gt: { name: 'Guatemala', img: 'flags/gt.png' },
  gu: { name: 'Guam', img: 'flags/gu.png' },
  gw: { name: 'Guinea-Bissau', img: 'flags/gw.png' },
  gy: { name: 'Guyana', img: 'flags/gy.png' },
  hk: { name: 'Hong Kong', img: 'flags/hk.png' },
  hm: { name: 'Heard Island and McDonald Islands', img: 'flags/hm.png' },
  hn: { name: 'Honduras', img: 'flags/hn.png' },
  hr: { name: 'Croatia', img: 'flags/hr.png' },
  ht: { name: 'Haiti', img: 'flags/ht.png' },
  hu: { name: 'Hungary', img: 'flags/hu.png' },
  id: { name: 'Indonesia', img: 'flags/id.png' },
  ie: { name: 'Ireland', img: 'flags/ie.png' },
  il: { name: 'Israel', img: 'flags/il.png' },
  im: { name: 'Isle of Man', img: 'flags/im.png' },
  in: { name: 'India', img: 'flags/in.png' },
  io: { name: 'British Indian Ocean Territory', img: 'flags/io.png' },
  iq: { name: 'Iraq', img: 'flags/iq.png' },
  ir: { name: 'Iran, Islamic Republic of', img: 'flags/ir.png' },
  is: { name: 'Iceland', img: 'flags/is.png' },
  it: { name: 'Italy', img: 'flags/it.png' },
  je: { name: 'Jersey', img: 'flags/je.png' },
  jm: { name: 'Jamaica', img: 'flags/jm.png' },
  jo: { name: 'Jordan', img: 'flags/jo.png' },
  jp: { name: 'Japan', img: 'flags/jp.png' },
  ke: { name: 'Kenya', img: 'flags/ke.png' },
  kg: { name: 'Kyrgyzstan', img: 'flags/kg.png' },
  kh: { name: 'Cambodia', img: 'flags/kh.png' },
  ki: { name: 'Kiribati', img: 'flags/ki.png' },
  km: { name: 'Comoros', img: 'flags/km.png' },
  kn: { name: 'Saint Kitts and Nevis', img: 'flags/kn.png' },
  kp: { name: 'Korea, Democratic People\'s Republic of', img: 'flags/kp.png' },
  kr: { name: 'Korea, Republic of', img: 'flags/kr.png' },
  kw: { name: 'Kuwait', img: 'flags/kw.png' },
  ky: { name: 'Cayman Islands', img: 'flags/ky.png' },
  kz: { name: 'Kazakhstan', img: 'flags/kz.png' },
  la: { name: 'Laos (Lao People\'s Democratic Republic)', img: 'flags/la.png' },
  lb: { name: 'Lebanon', img: 'flags/lb.png' },
  lc: { name: 'Saint Lucia', img: 'flags/lc.png' },
  li: { name: 'Liechtenstein', img: 'flags/li.png' },
  lk: { name: 'Sri Lanka', img: 'flags/lk.png' },
  lr: { name: 'Liberia', img: 'flags/lr.png' },
  ls: { name: 'Lesotho', img: 'flags/ls.png' },
  lt: { name: 'Lithuania', img: 'flags/lt.png' },
  lu: { name: 'Luxembourg', img: 'flags/lu.png' },
  lv: { name: 'Latvia', img: 'flags/lv.png' },
  ly: { name: 'Libya', img: 'flags/ly.png' },
  ma: { name: 'Morocco', img: 'flags/ma.png' },
  mc: { name: 'Monaco', img: 'flags/mc.png' },
  md: { name: 'Moldova, Republic of', img: 'flags/md.png' },
  me: { name: 'Montenegro', img: 'flags/me.png' },
  mf: { name: 'Saint Martin', img: 'flags/mf.png' },
  mg: { name: 'Madagascar', img: 'flags/mg.png' },
  mh: { name: 'Marshall Islands', img: 'flags/mh.png' },
  mk: { name: 'North Macedonia', img: 'flags/mk.png' },
  ml: { name: 'Mali', img: 'flags/ml.png' },
  mm: { name: 'Myanmar', img: 'flags/mm.png' },
  mn: { name: 'Mongolia', img: 'flags/mn.png' },
  mo: { name: 'Macao', img: 'flags/mo.png' },
  mp: { name: 'Northern Mariana Islands', img: 'flags/mp.png' },
  mq: { name: 'Martinique', img: 'flags/mq.png' },
  mr: { name: 'Mauritania', img: 'flags/mr.png' },
  ms: { name: 'Montserrat', img: 'flags/ms.png' },
  mt: { name: 'Malta', img: 'flags/mt.png' },
  mu: { name: 'Mauritius', img: 'flags/mu.png' },
  mv: { name: 'Maldives', img: 'flags/mv.png' },
  mw: { name: 'Malawi', img: 'flags/mw.png' },
  mx: { name: 'Mexico', img: 'flags/mx.png' },
  my: { name: 'Malaysia', img: 'flags/my.png' },
  mz: { name: 'Mozambique', img: 'flags/mz.png' },
  na: { name: 'Namibia', img: 'flags/na.png' },
  nc: { name: 'New Caledonia', img: 'flags/nc.png' },
  ne: { name: 'Niger', img: 'flags/ne.png' },
  nf: { name: 'Norfolk Island', img: 'flags/nf.png' },
  ng: { name: 'Nigeria', img: 'flags/ng.png' },
  ni: { name: 'Nicaragua', img: 'flags/ni.png' },
  nl: { name: 'Netherlands', img: 'flags/nl.png' },
  no: { name: 'Norway', img: 'flags/no.png' },
  np: { name: 'Nepal', img: 'flags/np.png' },
  nr: { name: 'Nauru', img: 'flags/nr.png' },
  nu: { name: 'Niue', img: 'flags/nu.png' },
  nz: { name: 'New Zealand', img: 'flags/nz.png' },
  om: { name: 'Oman', img: 'flags/om.png' },
  pa: { name: 'Panama', img: 'flags/pa.png' },
  pe: { name: 'Peru', img: 'flags/pe.png' },
  pf: { name: 'French Polynesia', img: 'flags/pf.png' },
  pg: { name: 'Papua New Guinea', img: 'flags/pg.png' },
  ph: { name: 'Philippines', img: 'flags/ph.png' },
  pk: { name: 'Pakistan', img: 'flags/pk.png' },
  pl: { name: 'Poland', img: 'flags/pl.png' },
  pm: { name: 'Saint Pierre and Miquelon', img: 'flags/pm.png' },
  pn: { name: 'Pitcairn', img: 'flags/pn.png' },
  pr: { name: 'Puerto Rico', img: 'flags/pr.png' },
  ps: { name: 'Palestine', img: 'flags/ps.png' },
  pt: { name: 'Portugal', img: 'flags/pt.png' },
  pw: { name: 'Palau', img: 'flags/pw.png' },
  py: { name: 'Paraguay', img: 'flags/py.png' },
  qa: { name: 'Qatar', img: 'flags/qa.png' },
  re: { name: 'Réunion', img: 'flags/re.png' },
  ro: { name: 'Romania', img: 'flags/ro.png' },
  rs: { name: 'Serbia', img: 'flags/rs.png' },
  ru: { name: 'Russian Federation', img: 'flags/ru.png' },
  rw: { name: 'Rwanda', img: 'flags/rw.png' },
  sa: { name: 'Saudi Arabia', img: 'flags/sa.png' },
  sb: { name: 'Solomon Islands', img: 'flags/sb.png' },
  sc: { name: 'Seychelles', img: 'flags/sc.png' },
  sd: { name: 'Sudan', img: 'flags/sd.png' },
  se: { name: 'Sweden', img: 'flags/se.png' },
  sg: { name: 'Singapore', img: 'flags/sg.png' },
  sh: { name: 'Saint Helena, Ascension and Tristan da Cunha', img: 'flags/sh.png' },
  si: { name: 'Slovenia', img: 'flags/si.png' },
  sj: { name: 'Svalbard and Jan Mayen Islands', img: 'flags/sj.png' },
  sk: { name: 'Slovakia', img: 'flags/sk.png' },
  sl: { name: 'Sierra Leone', img: 'flags/sl.png' },
  sm: { name: 'San Marino', img: 'flags/sm.png' },
  sn: { name: 'Senegal', img: 'flags/sn.png' },
  so: { name: 'Somalia', img: 'flags/so.png' },
  sr: { name: 'Suriname', img: 'flags/sr.png' },
  ss: { name: 'South Sudan', img: 'flags/ss.png' },
  st: { name: 'Sao Tome and Principe', img: 'flags/st.png' },
  sv: { name: 'El Salvador', img: 'flags/sv.png' },
  sx: { name: 'Sint Maarten (Dutch part)', img: 'flags/sx.png' },
  sy: { name: 'Syrian Arab Republic', img: 'flags/sy.png' },
  sz: { name: 'Swaziland', img: 'flags/sz.png' },
  tc: { name: 'Turks and Caicos Islands', img: 'flags/tc.png' },
  td: { name: 'Chad', img: 'flags/td.png' },
  tf: { name: 'French Southern Territories', img: 'flags/tf.png' },
  tg: { name: 'Togo', img: 'flags/tg.png' },
  th: { name: 'Thailand', img: 'flags/th.png' },
  tj: { name: 'Tajikistan', img: 'flags/tj.png' },
  tk: { name: 'Tokelau', img: 'flags/tk.png' },
  tl: { name: 'Timor-Leste', img: 'flags/tl.png' },
  tm: { name: 'Turkmenistan', img: 'flags/tm.png' },
  tn: { name: 'Tunisia', img: 'flags/tn.png' },
  to: { name: 'Tonga', img: 'flags/to.png' },
  tr: { name: 'Turkey', img: 'flags/tr.png' },
  tt: { name: 'Trinidad and Tobago', img: 'flags/tt.png' },
  tv: { name: 'Tuvalu', img: 'flags/tv.png' },
  tw: { name: 'Taiwan (Republic of China)', img: 'flags/tw.png' },
  tz: { name: 'Tanzania, United Republic of', img: 'flags/tz.png' },
  ua: { name: 'Ukraine', img: 'flags/ua.png' },
  ug: { name: 'Uganda', img: 'flags/ug.png' },
  um: { name: 'US Minor Outlying Islands', img: 'flags/um.png' },
  us: { name: 'United States', img: 'flags/us.png' },
  uy: { name: 'Uruguay', img: 'flags/uy.png' },
  uz: { name: 'Uzbekistan', img: 'flags/uz.png' },
  va: { name: 'Holy See (Vatican City State)', img: 'flags/va.png' },
  vc: { name: 'Saint Vincent and the Grenadines', img: 'flags/vc.png' },
  ve: { name: 'Venezuela, Bolivarian Republic of', img: 'flags/ve.png' },
  vg: { name: 'Virgin Islands, British', img: 'flags/vg.png' },
  vi: { name: 'Virgin Islands, U.S.', img: 'flags/vi.png' },
  vn: { name: 'Vietnam', img: 'flags/vn.png' },
  vu: { name: 'Vanuatu', img: 'flags/vu.png' },
  wf: { name: 'Wallis and Futuna Islands', img: 'flags/wf.png' },
  ws: { name: 'Samoa', img: 'flags/ws.png' },
  xk: { name: 'Kosovo', img: 'flags/xk.png' },
  ye: { name: 'Yemen', img: 'flags/ye.png' },
  yt: { name: 'Mayotte', img: 'flags/yt.png' },
  za: { name: 'South Africa', img: 'flags/za.png' },
  zm: { name: 'Zambia', img: 'flags/zm.png' },
  zw: { name: 'Zimbabwe', img: 'flags/zw.png' }
};

export default flags;